### ISSUE TITLE
[help wanted] FileNotFoundError: [Errno 2] No such file or directory for --sopa resolve baysor

### ISSUE THREAD

**Issue by KunHHE** [gustaveroussy/sopa#161]
Hi,
Dear community, I finished Baysor segmentation and tried to run --sopa resolve baysor C:/Users/hekun/Downloads/S3R1.zarr --gene-column genes; But an error showed up: FileNotFoundError: [Errno 2] No such file or directory:
'C:\\Users\\hekun\\Downloads\\S3R1.zarr\\.sopa_cache\\baysor_boundaries\\0\\segmentation_polygons.json'

I know there's one report in #152 report. Yes, I did notice the output for the JSON file is segmentation_polygons_2d, but not segmentation_polygons. I guess renaming all the patch folders won't help? Any suggestions?

Thanks very very much!

**Comment by KunHHE** [comment]
Dear @quentinblampey, can I ask you the new version of sopa==2.0.0?  Thank you!!!

**Comment by quentinblampey** [comment]
Hello @KunHHE, it's still not released, I'm waiting for the new version of SpatialData. It should arrive soon, hopefully this week

**Comment by KunHHE** [comment]
Hi, @quentinblampey, is this a CLI-specific issue? If we switch to snakemake or API, is there no issue at all? Thank you so much! appy holidays!

**Comment by quentinblampey** [comment]
Hi @KunHHE, no it's not specific to the CLI, you'll also have the error using the API/pipeline.
Sorry for the delay regarding the release of sopa 2, I hope the new version of SpatialData will soon be released...

**Comment by quentinblampey** [comment]
Sorry for the delay!
I’m happy to announce that `sopa==2.0.0` is now released :)
Don’t hesitate to check the new documentation, or the [migration guide](https://github.com/gustaveroussy/sopa/discussions/138) to smoothly get up to date!

**Comment by KunHHE** [comment]
Wanderful @quentinblampey, when run sopa segmentation cellpose C:/Users/hekun/Downloads/Slide1316.zarr --diameter 60 --channels Cellbound2 --channels DAPI --flow-threshold 1.5 --cellprob-threshold -5.5 --pretrained-model C:/Users/hekun/.cellpose/models/CP_20250110_104912DRGv2 --min-area 1000 --clip-limit 0.2 --gaussian-sigma 1. 

How to run 'export SOPA_PARALLELIZATION_BACKEND=dask', so it will run segmentation in a parallelization manner?

Thank you!

**Comment by KunHHE** [comment]
Update: I create a .py file running in the CLI:
set SOPA_PARALLELIZATION_BACKEND=dask
python C:/Users/hekun/segmentation.py 

The segmentation.py file is: 

import sopa

sopa.settings.dask_client_kwargs['n_workers'] = 4  
sopa.settings.dask_client_kwargs['memory_limit'] = '16GB'
sopa.segmentation.cellpose(
    "C:/Users/hekun/Downloads/Slide1316.zarr",
    diameter=60,
    channels=["Cellbound2", "DAPI"],
    flow_threshold=1.5,
    cellprob_threshold=-5.5,
    pretrained_model="C:/Users/hekun/.cellpose/models/CP_20250110_104912DRGv2",
    min_area=1000,
    clip_limit=0.2,
    gaussian_sigma=1
)

Error: 

(sopa) C:\Users\hekun>python C:/Users/hekun/segmentation.py
C:\Users\hekun\miniconda3\envs\sopa\lib\site-packages\dask\dataframe\__init__.py:31: FutureWarning: The legacy Dask DataFrame implementation is deprecated and will be removed in a future version. Set the configuration option `dataframe.query-planning` to `True` or None to enable the new Dask Dataframe implementation and silence this warning.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\hekun\segmentation.py", line 8, in <module>
    sopa.segmentation.cellpose(
  File "C:\Users\hekun\miniconda3\envs\sopa\lib\site-packages\sopa\segmentation\methods\_cellpose.py", line 71, in cellpose
    custom_staining_based(
  File "C:\Users\hekun\miniconda3\envs\sopa\lib\site-packages\sopa\segmentation\methods\_custom.py", line 41, in custom_staining_based
    temp_dir = get_cache_dir(sdata) / cache_dir_name
  File "C:\Users\hekun\miniconda3\envs\sopa\lib\site-packages\sopa\utils\utils.py", line 293, in get_cache_dir
    if sdata.is_backed():  # inside the zarr directory
AttributeError: 'str' object has no attribute 'is_backed'

**Comment by quentinblampey** [comment]
Hi @KunHHE,

For the first example, in simply means that you have too many workers with too few memory. You can use a different machine, or, as you tried, use a different number of workers, as described below. For the second, you actually try to use the API, whose usage is described [in this tutorial](https://gustaveroussy.github.io/sopa/tutorials/api_usage/). In particular, the API uses directly the SpatialData object as an input, not paths. So, the command `sopa.segmentation.cellpose(
"C:/Users/hekun/Downloads/Slide1316.zarr", ...)` is wrong and should be `sopa.segmentation.cellpose(sdata, ...)` (I let you read the above tutorial to know more).

So, finally, it should look like so:
```python
import sopa

sopa.settings.parallelization_backend = "dask"
sopa.settings.dask_client_kwargs["n_workers"] = 4

sopa.segmentation.cellpose(sdata, ...) # add the other arguments

... # continue using the API
```

**Comment by KunHHE** [comment]
so "sopa.settings.parallelization_backend = "dask"; sopa.settings.dask_client_kwargs["n_workers"] = 4"  cannot be done in the CLI, so API only?

**Comment by KunHHE** [comment]
OK, Assuming the API can be run using jupyter notebook, so I tried and looks like it worked out:

![Image](https://github.com/user-attachments/assets/c66cfe87-ee4a-4ff7-b6dc-8d1d56fad04e)

![Image](https://github.com/user-attachments/assets/6062e28e-4375-42af-a37b-268ae5256095)

![Image](https://github.com/user-attachments/assets/07a56a03-7738-4cfc-93ec-fc6a7107d4cc)

**Comment by quentinblampey** [comment]
Yes, using the API means you can use a Jupyter Notebook, among others.

> so "sopa.settings.parallelization_backend = "dask"; sopa.settings.dask_client_kwargs["n_workers"] = 4" cannot be done in the CLI, so API only?

It can be done using the CLI, but the command is different. For the CLI, you need to [set an environment variable](https://gustaveroussy.github.io/sopa/faq/#how-to-parallelize-segmentation), as you did above. The thing is, this only sets dask, but you can't (yet) choose the number of workers via the CLI. I can add this, but, meanwhile, prefer using the API or you can also use a machine with more RAM per worker

**Comment by KunHHE** [comment]
Thanks very much! @quentinblampey, sorry too many questions. I have to run Baysor using cellpose as prior, so want to double-check, I am using API now, do we still need the .toml for Baysor config? 

OR we just need te default setting using: 
sopa.make_transcript_patches(sdata, patch_width=1000, prior_shapes_key="cellpose_boundaries")
sopa.segmentation.baysor(sdata, min_area=20)
sopa.aggregate(sdata)

For "resolve", both Cellpose and Baysor running in the sopa, it will always automatically run resolve NOW?

**Comment by quentinblampey** [comment]
You can provide a baysor config, as detailed in the tutorial, but you don't have to. If you don't provide a baysor config, it will be inferred. But if you already have a good config, it's easier to use.

Yes, you don't need to run "resolve" using the API.

**Comment by KunHHE** [comment]
Cool! If I run sopa.segmentation.tissue(sdata) prior to "sopa.make_image_patches(sdata, patch_width=6000, patch_overlap=150)" and  "sopa.segmentation.cellpose", will te patches and segmentation run the "region_of_interest" region only?

**Comment by KunHHE** [comment]
I think the sopa2.0 running on cellpose is kind of slower compared to the older version of sopa?, even I used CLI mode.

**Comment by KunHHE** [comment]
Thanks so much @quentinblampey, I was stopped by Baysor running. I can run it before using CLI. Now I am using the API.

 sopa.segmentation.baysor(sdata, min_area=20), error is "FileNotFoundError: Please install baysor and ensure that either `C:\Users\hekun\.julia\bin\baysor` executes baysor, or `baysor` is an existing shell alias for baysor's executable."
I set up "Environment Variable" window and add C:\Users\hekun\.julia\bin\ to the path. Then I opened PowerShell: Baysor and it recognized it.  ---"PS C:\Users\hekun> baysor"---"  baysor v0.7.1".

I freshened the notebook and 'env', but still the sopa cannot find the baysor's executable.
Could you please provide any guidance?

Thanks!

**Comment by KunHHE** [comment]
Updates: figure it out using 
import os
os.environ["PATH"] += os.pathsep + r"C:\Users\hekun\.julia\bin"

But I had issues:
1. on some patches <4000 transcripts are out for segmentation, so only few patche(s) were added to sdata['transcripts_patches'], then how to force it to run all patches?

![Image](https://github.com/user-attachments/assets/bd2df0bb-d9f6-4035-a8b4-1e052b3ba5f4)

2. Then run sopa.segmentation.baysor(sdata, min_area=20)
error: AssertionError: Could not find the segmentation polygons file in C:\Users\hekun\Downloads\Slide1307.zarr\.sopa_cache\transcript_patches\3
But I can see patch 3 in the folder of the .zarr, can you guide me on how to debug it?

[INFO] (sopa.segmentation.methods._baysor) The Baysor config was not provided, using the following by default:
{'data': {'x': 'x', 'y': 'y', 'gene': 'gene', 'min_molecules_per_gene': 10, 'min_molecules_per_cell': 20, 'force_2d': True}, 'segmentation': {'prior_segmentation_confidence': 0.8}}
[WARNING] (sopa._settings) Running without parallelization backend can be slow. Consider using a backend, e.g. via `sopa.settings.parallelization_backend = 'dask'`, or `export SOPA_PARALLELIZATION_BACKEND=dask`.
100%|███████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 124.03it/s]
[INFO] (sopa.segmentation._transcripts) Cells whose area is less than 20 microns^2 will be removed
Reading transcript-segmentation outputs:   0%|                                                   | 0/4 [00:00<?, ?it/s]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[22], line 1
----> 1 sopa.segmentation.baysor(sdata, min_area=20)

File ~\miniconda3\envs\sopa\lib\site-packages\sopa\segmentation\methods\_baysor.py:79, in baysor(sdata, config, min_area, delete_cache, recover, force, scale, key_added, patch_index)
     76     assert patches_dirs, "Baysor failed on all patches"
     78 gene_column = _get_gene_column_argument(config)
---> 79 resolve(sdata, patches_dirs, gene_column, min_area=min_area, key_added=key_added)
     81 sdata.attrs[SopaAttrs.BOUNDARIES] = key_added
     83 if delete_cache:

File ~\miniconda3\envs\sopa\lib\site-packages\sopa\segmentation\_transcripts.py:43, in resolve(sdata, patches_dirs, gene_column, min_area, key_added)
     40 if min_area > 0:
     41     log.info(f"Cells whose area is less than {min_area} microns^2 will be removed")
---> 43 patches_cells, adatas = _read_all_segmented_patches(patches_dirs, min_area)
     44 geo_df, cells_indices, new_ids = _resolve_patches(patches_cells, adatas)
     46 points_key = sdata[SopaKeys.TRANSCRIPTS_PATCHES][SopaKeys.POINTS_KEY].iloc[0]

File ~\miniconda3\envs\sopa\lib\site-packages\sopa\segmentation\_transcripts.py:142, in _read_all_segmented_patches(patches_dirs, min_area)
    138 def _read_all_segmented_patches(
    139     patches_dirs: list[str],
    140     min_area: float = 0,
    141 ) -> tuple[list[list[Polygon]], list[AnnData]]:
--> 142     outs = [
    143         _read_one_segmented_patch(path, min_area)
    144         for path in tqdm(patches_dirs, desc="Reading transcript-segmentation outputs")
    145     ]
    147     patches_cells, adatas = zip(*outs)
    149     return patches_cells, adatas

File ~\miniconda3\envs\sopa\lib\site-packages\sopa\segmentation\_transcripts.py:143, in <listcomp>(.0)
    138 def _read_all_segmented_patches(
    139     patches_dirs: list[str],
    140     min_area: float = 0,
    141 ) -> tuple[list[list[Polygon]], list[AnnData]]:
    142     outs = [
--> 143         _read_one_segmented_patch(path, min_area)
    144         for path in tqdm(patches_dirs, desc="Reading transcript-segmentation outputs")
    145     ]
    147     patches_cells, adatas = zip(*outs)
    149     return patches_cells, adatas

File ~\miniconda3\envs\sopa\lib\site-packages\sopa\segmentation\_transcripts.py:93, in _read_one_segmented_patch(directory, min_area, min_vertices)
     89 def _read_one_segmented_patch(
     90     directory: str, min_area: float = 0, min_vertices: int = 4
     91 ) -> tuple[list[Polygon], AnnData]:
     92     directory: Path = Path(directory)
---> 93     id_as_string, polygon_file = _find_polygon_file(directory)
     95     loom_file = directory / "segmentation_counts.loom"
     96     if loom_file.exists():

File ~\miniconda3\envs\sopa\lib\site-packages\sopa\segmentation\_transcripts.py:134, in _find_polygon_file(directory)
    132     return False, old_baysor_path
    133 new_baysor_path = directory / "segmentation_polygons_2d.json"
--> 134 assert new_baysor_path.exists(), f"Could not find the segmentation polygons file in {directory}"
    135 return True, new_baysor_path

AssertionError: Could not find the segmentation polygons file in C:\Users\hekun\Downloads\Slide1307.zarr\.sopa_cache\transcript_patches\3

**Comment by quentinblampey** [comment]
You can use `min_points_per_patch=0`, which will make Baysor run even on patches with a low amount of transcripts
But the way to force baysor running is by using `sopa.segmentation.baysor(sdata, min_area=0, force=True)`

Please, next time, can you try to send a way for me to reproduce your issue? I.e., using the toy dataset for instance.
Also, the documentation should answer already most of your questions!

**Comment by KunHHE** [comment]
Hi @quentinblampey Thanks for suggestions, I did use Toy data for testing for Baysor, and it phenocopys the issue that there's no segmentation polygons file in the .sopa_cache\transcript_patches\. I share the notebook for your reference via OneDrive link, hope it works!

https://esbc22-my.sharepoint.com/:u:/g/personal/kun_he_omapix_com/EaRLYnQhzoVJlEATvb_xI5MBM5bdwE8QFMEAvmbYTXabxQ?e=AsP4xr

**Comment by KunHHE** [comment]
Yeah, I re-installed the BAYSOR dependencies. using CLI:
installe Julia and GCC;
juliaup add 1.10;
juliaup default 1.10;
julia -e "using Pkg; Pkg.add(PackageSpec(url="https://github.com/kharchenkolab/Baysor.git")); Pkg.build()"

Then in the CLI I test: 'baysor segfree -c C:/Users/hekun/sopa/workflow/config/merscope/merscope.toml C:/Users/hekun/Downloads/Slide1307/detected_transcripts.csv', looks it is working in the baysor itself?

![Image](https://github.com/user-attachments/assets/64a6e09f-d39d-449e-be2b-70dbb797cd51)

**Comment by quentinblampey** [comment]
Thanks for trying this! And do you have the results of Baysor somewhere?
Other question: when running baysor with Sopa, does it look like something is running, or is it super quick until the error?

**Comment by KunHHE** [comment]
Hi @quentinblampey. 
Run baysor segfree, i get a loom file: https://esbc22-my.sharepoint.com/:u:/g/personal/kun_he_omapix_com/ES9YzbLO7l9FmLHOUBfL4bIBXJf0nIty-1LixSvi1BwN6Q?e=sES6kn
and a log: https://esbc22-my.sharepoint.com/:u:/g/personal/kun_he_omapix_com/EbATSTvQBX9En-1T8DYF-3kBS7i2wI_R8lncA-jPlQFzpQ?e=UKvPTn

I did sopa[baysor] install, then installed julia 1.10 and open julia; 
Then: using Pkg
Pkg.add(PackageSpec(url="https://github.com/kharchenkolab/Baysor.git"))
Pkg.build()
Then I go to sopa env using miniconda3 prompt:
pip install julia;
import julia
julia.install();

I did not see error during those installation process.

Then tried to go back to sopa notebook using Toy data, run baysor, it runs the first stage but failed for patches call:

sopa.segmentation.baysor(sdata,
                         config=None,
                         min_area=0,
                         delete_cache=True,
                         recover=False,
                         force=True,
                         scale=None,
                         key_added='BAYSOR_BOUNDARIES',
                         patch_index=None)
--------------detailed track:
[INFO] (sopa.segmentation.methods._baysor) The Baysor config was not provided, using the following by default:
{'data': {'x': 'x', 'y': 'y', 'gene': 'genes', 'min_molecules_per_gene': 10, 'min_molecules_per_cell': 20, 'force_2d': True}, 'segmentation': {'prior_segmentation_confidence': 0.8}}

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.98it/s]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[25], line 1
----> 1 sopa.segmentation.baysor(sdata,
      2                          config=None,
      3                          min_area=0,
      4                          delete_cache=True,
      5                          recover=False,
      6                          force=True,
      7                          scale=None,
      8                          key_added='BAYSOR_BOUNDARIES',
      9                          patch_index=None)

File ~\miniconda3\envs\sopa\lib\site-packages\sopa\segmentation\methods\_baysor.py:76, in baysor(sdata, config, min_area, delete_cache, recover, force, scale, key_added, patch_index)
     74 if force:
     75     patches_dirs = [patch_dir for patch_dir in patches_dirs if (patch_dir / "segmentation_counts.loom").exists()]
---> 76     assert patches_dirs, "Baysor failed on all patches"
     78 gene_column = _get_gene_column_argument(config)
     79 resolve(sdata, patches_dirs, gene_column, min_area=min_area, key_added=key_added)

AssertionError: Baysor failed on all patches

**Comment by KunHHE** [comment]
Updates: I run the baysor patch-by-patch one by one manually in the CLI successfully using:
cd C:/Users/hekun/Downloads/Slide1307.zarr/.sopa_cache/transcript_patches/8;
Then: C:/Users/hekun/.julia/bin/baysor run --polygon-format FeatureCollection -c /Users/hekun/sopa/workflow/config/merscope/merscope.toml transcripts.csv.

In the API, after run :sopa.make_transcript_patches(sdata,
                             patch_width=500,
                             patch_overlap=20,
                             points_key=None,
                             prior_shapes_key="cellpose_boundaries",
                             unassigned_value=None,
                             min_points_per_patch=0,
                             write_cells_centroids=False,
                             key_added=None), it generate transcript_patches in the .sopa_cache folder,
Then we run: sopa.segmentation.baysor(sdata,
                         config="C:/Users/hekun/sopa/workflow/config/merscope/merscope.toml",
                         min_area=0,
                         delete_cache=True,
                         recover=False,
                         force=True,
                         key_added='baysor_boundaries',
                         patch_index=None,
                         cache_dir='C:/Users/hekun/Downloads/Slide1307.zarr/.sopa_cache/transcript_patches'
                        ), then looks like the program is looking segmentation polygons file (segmentation_polygons_2d?), but the segmentation_polygons_2d file for each patch is the outputs?

**Comment by KunHHE** [comment]
Hi @quentinblampey, I tested using ubuntu, and it worked out. looks like there are some issue running in windows?

**Comment by quentinblampey** [comment]
@KunHHE do you still experience this issue on Windows? It should work on the last version of Sopa

**Comment by KunHHE** [comment]
Thanks @quentinblampey, I am running sopa in Ubuntu subsystem, and did not go back to Windows for testing. But I can go back to Windows for testing. And by the way, since you know Baysor might be a little complicated for some dependencies when removing old version of sopa, so is there a way we just update the sopa version under this Python env only? Or I can just simply do an update with no impact on Baysor dependencies? Thanks!

**Comment by quentinblampey** [comment]
Yes you can definitely update `sopa` alone, i.e. without any Baysor update
